### ISSUE TITLE
Email field on Contact object

### ISSUE THREAD

**Issue by ghost** [Zingle/rest-api-documentation#12]
Hi @njovin , hope you are doing well.

When I have a look at the documentation regarding the Contact object, I can't find email field.
https://github.com/Zingle/rest-api-documentation/blob/master/contacts/README.md

But I can see there is a functionality on the dashboard so we can set email for each contact.
https://prnt.sc/wkrvos

Can you please let me know how I can retrieve the email information for each contact?

Thanks.

**Comment by njovin** [comment]
@bloolight thanks for reaching out.  Email is treated as a channel and as such can be controlled using that endpoint (https://github.com/Zingle/rest-api-documentation/tree/master/contact_channels).  

For quicker service in the future, please reach out to Zingle support directly.  We don't normally monitor the issues here.
