### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by earthy-birdy** [Zingle/rest-api-documentation#13]
Hello there. we are using Zingle API to dvelop a web app. It worked for a couple of times, but now it doesn't. 
We get the following error when doing a request using a post method:
 (https://api.zingle.me/v1/services/{{service_id}}/messages) in postmand, it works. Also we installed this [extension](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) and the web app works fine.
the error we get when running the web app without this extension on a Chrome browser is this:
Http failure response for https://api.zingle.me/v1/services/2f662005-3124-41d9-bac9-ff94675b745b/messages: 0 Unknown Error
how come we debug this error or solve it?

**Comment by earthy-birdy** [comment]
when trying to find errors on the Chrome console, I get this 2 errors:
1- Access to XMLHttpRequest at 'https://api.zingle.me/v1/services/bunch-of-numbers-here]/messages' from origin 'https://highkeystaff.web.' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
2-  https://api.zingle.me/v1/services/[bunchofnumbers]/messages net::ERR_FAILED

**Comment by richRemer** [comment]
This is likely by design. The browser is rejecting the request because it's trying to do something dangerous, namely set the Authorization header for another site. This could - among other things - allow any website to inject code and turn all their visitors into a bot network to brute force our passwords.
