### ISSUE TITLE
UNIX timestamps returned by API are inconsistent (seconds vs. milliseconds)

### ISSUE THREAD

**Issue by putnam** [Zingle/rest-api-documentation#2]
I'm setup as a hotel client with Zingle. There are "check-in" and "check-out" custom fields available for contacts which can be set in the web UI to a fixed date. When pulled via API, these fields are GMT timestamps, but are in _milliseconds_ since the epoch rather than seconds. As far as I can tell, all other timestamps (like created_at and updated_at) are in _seconds_ since the epoch. The documentation says all timestamps are in seconds.

Note that in Javascript, "UNIX timestamps" via Date.now() are in milliseconds since the epoch, so I'm guessing that's the source of the incorrect units.

Solution:
- Fix documentation to indicate the differences or
- Fix timestamp on checkin/checkout to be consistent with documentation and other fields

The latter of course could be API breaking for some clients. I'm currently just special casing those fields.

**Comment by putnam** [comment]
I also cannot _set_ this value with the same number that I _get_. If I provide a timestamp (seconds or milliseconds), checkin/checkout times are not updated and end up set to 0. This happens whether the timestamp is provided as a number or a string.

If I send a date like "2016-04-01" the values are updated correctly. This is inconsistent with how the values are _retrieved_ through the API, which comes out as milliseconds since the epoch.

**Comment by davidmpeace** [comment]
Thanks for the detailed report.  We are looking into the issue.

**Comment by putnam** [comment]
I see this has been worked on, and there's a helpful error message to correct clients who are still using string based dates.

However now I can't create contacts at all with the API. I'm getting an opaque 500 server error. I'm providing the checkin/checkout times as timestamps (seconds) in the initial custom_field_values list during the create contact call. Even if I don't provide these fields (leaving just first name and last name) I get the 500 error.

Are your unit tests working on the create contact endpoint? We currently can't import people from our property management system into Zingle due to this error. Maybe it's my fault?

**Comment by putnam** [comment]
Looks like the contacts actually get created and the values are set right, but the server response is wrong.

**Comment by njovin** [comment]
@putnam Thanks for the report.  We've released an update which fixes this issue.
